[pytest]
addopts = --clean-alluredir --headed --slowmo 3000 -v  --base-url http://localhost:3000 --alluredir=allure-results --screenshot=only-on-failure
testpaths = tests
pythonpath = .


markers =
    smoke
    regression